### ISSUE TITLE
Remove control messages from /query endpoint with an option

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2256] opened 2022-03-07 19:23 UTC
From slack:
> BUG.  If you export as ZNG, and run zq on results.zng, you get an error message “control”.  This is because the downloaded ZNG has control messages and zq barfs on them. 

The backend used to have an option called `noctrl` that would remove these messages. As of the zed main, that text no longer appears in the code.

**Comment by philrz** [comment] 2022-07-19 22:56
I've just stumbled onto this issue and recognize it as a duplicate of #2444, which was recently fixed.

Closing as a duplicate.

**Closed by philrz** 2022-07-19 22:56 UTC
Labels: bug
