### ISSUE TITLE
Refresh Pool List

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2398] opened 2022-06-14 19:57 UTC
If we can do this automatically, let's take advantage of that. Otherwise, let's add a menu option to refresh the list.

Originally requested on Slack: https://brimdata.slack.com/archives/C010DR0HHMF/p1655218483244169

**Comment by philrz** [comment] 2022-06-27 23:29
Repro video from the Slack thread:

![pooltest](https://user-images.githubusercontent.com/5934157/176053557-85979a18-10d1-465a-a862-ffdfa8fff613.gif)

And more insight from @nwt:

> GIF shows pool creation via Python, which talks to zed serve, so the app should receive a pool-new event and update. It doesn’t update, so there’s a bug here, right?

**Comment by philrz** [comment] 2022-07-20 22:45
This issue is effectively a duplicate of https://github.com/brimdata/zed/issues/3924. Whereas that issue was repro'ed/verified using the `zed` client, since the original repro of this specific issue was using the Python client, here's verification that's working using Brim commit 55d1fdc which uses Zed commit `d10050f` and the Python client.

https://user-images.githubusercontent.com/5934157/180095043-2b5c3d8d-031d-4233-8246-fb6d5f1c3ff0.mp4

Thanks @nwt!

**Closed by philrz** 2022-07-20 22:45 UTC
Labels: duplicate
