### ISSUE TITLE
Make "count by field" always available in cells (regression at a975297)

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2250] opened 2022-03-06 14:59 UTC
Steve from slack
> BUG… I’m on tip of main and if I right-click on count-by-field it rewrites the query but the results window doesn’t change…

> Then if I go to the search bar and hit return, I get the updated results…

**Comment by philrz** [comment] 2022-03-21 16:58
I bumped into this one as well and was about to file a bug and found this existing one. Since I'd already done the detailed repro work, I'll add all that info here in case it helps.

My current repro is with Brim commit 12c1629. As shown in the attached video, my steps:

1. Drag the attached [data.json.gz](https://github.com/brimdata/brim/files/8317402/data.json.gz) into the app
2. Execute the query `count() by foo`, which gives the expected table of results
3. As described in the original bug descirpiton, a right-click "Pivot to logs" rewrites the query correctly to `foo=="baz"` but the results are _not_ narrowed as they should be
4. Hitting Enter to re-execute the query _does_ narrow the results correctly

https://user-images.githubusercontent.com/5934157/159320063-839c9009-39e3-4df6-bed0-eae4c01dfcf2.mp4

I also did some binary search to see where the problem first appeared and it looks like it was a regression at commit a975297b81186d576e8ff31858a72a1a5224caed which is associated with #2124.

**Comment by philrz** [comment] 2022-08-22 16:55
I'm pleased to report that this one seems to have gone away on its own. The video below is taken with current Brim commit 5b132f5. I also determined via binary search that this started working as commit 798e664 (#2327), which admittedly looks like a pretty huge set of deltas so I have no clue what made the difference. In any case, closing as fixed.

https://user-images.githubusercontent.com/5934157/185976493-f949f4a8-1ed9-4a16-b22a-3f2bc1db2d2c.mp4

**Closed by philrz** 2022-08-22 16:55 UTC
Labels: bug

**Comment by jameskerr** [comment] 2022-08-22 17:07
Cool
