### ISSUE TITLE
Brim does not use suricata rules

### ISSUE THREAD

**Issue by polunika** [brimdata/brim#2304] opened 2022-04-04 07:05 UTC
Hi all,

currently I am doing some challenges from cyberdefenders.org. Therefore, I am using Brim to analyze the provided pcaps.
Unfortunately, the listing of Suricata-alerts doesn't work well in my opinion.
When I use the base configuration, Brim shows 8 results with the following filter: event_type=="alert" | alerts := union(alert.category) by src_ip, dest_ip
When I delete the file suricata.rules from the directory /opt/Brim/resources/app.asar.unpacked/zdeps/suricata/var/lib/suricata/rules/, Brim shows me the same 8 results with the above filter after restarting and importing the pcap again.
Even if I replace the file suricata.rules with a provided file from cyberdefenders, Brim shows the same 8 results like before.
From a blog-post (https://ellisstannard.medium.com/malware-traffic-analysis-3-c4c47757e184) I know, that it is possible to list more results with the corresponding filter, but I think I am missing something....

Is it correct, that Brim uses the suricata.rules from the above path automatically or is there another file or directory, that is used?

Thanks in advance

**Comment by mattnibs** [comment] 2022-04-04 18:10
Closing duplicate of https://github.com/brimdata/brimcap/issues/233, we'll track this issue there.

**Closed by mattnibs** 2022-04-04 18:10 UTC
