### ISSUE TITLE
Graph Timestamp does not match PCAP Timestamp

### ISSUE THREAD

**Issue by jsthomason** [brimdata/brim#1507] opened 2021-03-16 12:51 UTC
Before opening a new issue, please make sure you've reviewed the troubleshooting guide:
https://github.com/brimsec/brim/wiki/Troubleshooting

**Describe the bug**
Graph Timestamp does not match PCAP timestamps nor System TZ

**To Reproduce**
My system time is US/Pacific, while the .pcap is US/Eastern; PCAP time is correct; Range selector is correct; Graph time appears to stay at UTC.

**Expected behavior**
Graph timestamps should match PCAP timestamps.

**Screenshots**

**Desktop Info**
[Please complete the following information]
 - OS: Ubuntu 18.04
 - Brim Version 0.24.0

**Comment by philrz** [comment] 2021-04-02 00:00
Hello again @jsthomason. Since I've not seen another update from you in a couple weeks, I'm going to go ahead and close this one as a duplicate of #1057. Please do keep an eye on that one and feel free to comment more over there if you'd like. Thanks for your help improving Brim!

**Closed by philrz** 2021-04-02 00:00 UTC
Labels: bug
