### ISSUE TITLE
supports only version 14 magic files

### ISSUE THREAD

**Issue by jrespeto** [brimdata/brim#1768] opened 2021-08-07 20:36 UTC
Before opening a new issue, please make sure you've reviewed the troubleshooting guide:
https://github.com/brimdata/brim/wiki/Troubleshooting

**Describe the bug**
Getting error:

```
Unable to generate full summary logs from PCAP 
Detail: /usr/lib/brim/resources/app/zdeps/suricata/suricatarunner exited with status 1: 7/8/2021 -- 16:21:57 - <Error> - [ERRCODE: SC_ERR_MAGIC_LOAD(197)] - magic_load failed: File 5.32 supports only version 14 magic files. `/etc/magic.mgc' is version 16
```

**To Reproduce**
On arch using trizen to install 
Try loading a pcap. 

**Expected behavior**
First time using - Don't know 

**Screenshots**
![image](https://user-images.githubusercontent.com/5333000/128613112-b59ae2c0-68e1-4e49-ae81-3219c3a37ca8.png)

**Desktop Info**
 - OS: Linux
 - Brim Version: 0.24
![image](https://user-images.githubusercontent.com/5333000/128613226-48005b03-f89f-49c3-b22c-828732d8171c.png)

**Comment by philrz** [comment] 2021-08-09 12:43
Hi @jrespeto. Thanks for your interest in Brim.

We've actually already addressed this issue in the code base and the fix is due to go out in our next GA release. We've been dealing with some delays wrapping up the next release so I don't have a date to give you for when that will be available. However, we've been making beta releases available to users in the community, so if you're interested in seeing this working sooner, feel free to join our public Slack via the invite link [https://www.brimsecurity.com/join-slack/](https://www.brimsecurity.com/join-slack/), join the #beta channel there, and if you scroll back in that channel you'll see the download links for the most recent beta version. In the meantime I'll hold this issue open and post a comment when the next GA release comes out, unless I should hear from you on Slack that you tried the beta and it's working adequately for you. Hope that helps!

**Comment by philrz** [comment] 2021-09-14 23:30
Hi again @jrespeto. Not sure if you saw the announcement, but the new GA Brim release `v0.25.0` just came out. You can find the links to download at [https://www.brimsecurity.com/download/](https://www.brimsecurity.com/download/) and there's also release notes linked from there.

I just booted an Arch Linux VM and confirmed that I was able to use `debtap` to install this new Brim release and now I can import pcaps without any complaints about the magic files. I see the package at [https://aur.archlinux.org/packages/brim/](https://aur.archlinux.org/packages/brim/) has not yet been updated and those of us here at Brim-the-company don't actually control that, but today I messaged the community member on our Brim public Slack who I think looks after it to inquire about if he can update it. If you're at all involved in that, please feel free to join up on the Slack system by following the [https://www.brimsecurity.com/join-slack/](https://www.brimsecurity.com/join-slack/) link and find me on there (username "phil") and we can discuss.

Since I think everything is working, I'm going to close this issue now. Thanks again for reporting!

**Closed by philrz** 2021-09-14 23:30 UTC
Labels: bug, community
